src/main/java/com/realive/controller/admin/AdminPenaltyController.java
src/main/java/com/realive/controller/seller/SellerController.java
src/main/java/com/realive/dto/logs/PenaltyLogCreateRequest.java
src/main/java/com/realive/repository/logs/PenaltyLogRepository.java
src/main/java/com/realive/service/admin/logs/AdminPenaltyService.java

 [Fix] 고객 패널티 타입 수정

---

build.gradle
src/main/java/com/realive/config/WebClientConfig.java
src/main/java/com/realive/security/customer/CustomerJwtAuthenticationFilter.java
src/main/java/com/realive/service/customer/CustomerService.java

[Fix] LocalDate 직렬화, Customer JWT, Config 수정

[Fix] LocalDate 직렬화, Customer JWT, Config 수정

---

src/main/java/com/realive/dto/auction/AuctionResponseDTO.java
src/main/java/com/realive/repository/customer/productview/ProductSearchImpl.java
src/main/java/com/realive/serviceimpl/admin/auction/AuctionServiceImpl.java

`auction/list` 상태
```
let matchesStatus = true;
if (statusFilter === 'PROCEEDING') {
matchesStatus = a.statusText === '진행중';
} else if (statusFilter === 'SCHEDULED') {
matchesStatus = a.statusText === '예정';
} else if (statusFilter === 'COMPLETED') {
matchesStatus = a.statusText === '종료';
}
```

[Edit] 경매 상태 텍스트 추가

---

src/main/java/com/realive/config/SecurityConfig.java

Team2/jaehyun [BE] css 적용을위한 백엔드 수정

[Edit] CSS 적용을 위한 BE 수정 

---

src/main/java/com/realive/controller/review/ReviewController.java
src/main/java/com/realive/dto/order/OrderItemResponseDTO.java
src/main/java/com/realive/service/order/OrderServiceImpl.java
src/main/java/com/realive/service/review/crud/ReviewCRUDService.java
src/main/java/com/realive/service/review/crud/ReviewCRUDServiceImpl.java

[WIP] review 중복 체크 로직 구현 중

---

src/main/java/com/realive/controller/admin/ranking/AdminSellerRankingController.java
src/main/java/com/realive/controller/product/CategoryController.java
src/main/java/com/realive/controller/public_api/ProductViewController.java
src/main/java/com/realive/domain/order/Order.java
src/main/java/com/realive/dto/admin/review/SellerRankingDTO.java
src/main/java/com/realive/dto/product/FeaturedProductSummaryResponseDTO.java
src/main/java/com/realive/dto/product/FeaturedSellerProductsResponseDTO.java
src/main/java/com/realive/repository/product/ProductRepository.java
src/main/java/com/realive/repository/review/SellerReviewRepository.java
src/main/java/com/realive/service/admin/logs/StatService.java
src/main/java/com/realive/service/product/ProductService.java
src/main/java/com/realive/serviceimpl/admin/log/StatServiceImpl.java
src/main/java/com/realive/serviceimpl/product/ProductServiceImpl.java

오늘의 판매자 상품 추천

---

src/main/java/com/realive/repository/customer/CustomerQnaRepository.java
src/main/java/com/realive/service/product/ProductService.java
src/main/java/com/realive/serviceimpl/product/ProductServiceImpl.java

Team1/javcki-new PR to dev

---

build.gradle

[Fix] 고객Q&A 수정

---

src/main/java/com/realive/config/SecurityConfig.java
src/main/java/com/realive/controller/review/ReviewController.java
src/main/java/com/realive/domain/order/Order.java

"/api/customer/auctions/**").permitAll() 에서
"/api/auctions/**").permitAll()
로 변경

[WIP]경매페이지를위한 security 수정

---

src/main/java/com/realive/config/SecurityConfig.java

.requestMatchers("/api/public/**", "/api/auth/**","/api/auctions/**").permitAll() 에서
.requestMatchers("/api/public/**", "/api/auth/**").permitAll()
로 변경

[WIP]경매페이지를위한 security 수정2

---

build.gradle
src/main/java/com/realive/controller/seller/SellerOrderDeliveryController.java
src/main/java/com/realive/controller/seller/SellerPayoutController.java
src/main/java/com/realive/dto/logs/PayoutLogDetailDTO.java
src/main/java/com/realive/dto/seller/SellerOrderDetailResponseDTO.java
src/main/java/com/realive/dto/seller/SellerPayoutSummaryDTO.java
src/main/java/com/realive/repository/order/OrderDeliveryRepository.java
src/main/java/com/realive/repository/order/OrderItemRepository.java
src/main/java/com/realive/repository/order/OrderRepository.java
src/main/java/com/realive/service/order/SellerOrderService.java
src/main/java/com/realive/service/seller/SellerPayoutService.java
src/main/java/com/realive/serviceimpl/order/SellerOrderServiceImpl.java
src/main/java/com/realive/serviceimpl/seller/SellerPayoutScheduler.java
src/main/java/com/realive/serviceimpl/seller/SellerPayoutServiceImpl.java

[Fix]정산관리 및 주문관리 백엔드 수정

---

src/main/java/com/realive/controller/seller/SellerController.java

[Fix]회원 정보 수정 기능 수정

---

src/main/java/com/realive/service/customer/CustomerQnaService.java

[Fix] 판매자 큐엔에이 수정

---

src/main/java/com/realive/controller/seller/SellerAdminQnaController.java
src/main/java/com/realive/domain/seller/SellerQna.java

[Fix] 관리자 문의 기능 추가 및 Seller_qna 수정

---

src/main/java/com/realive/config/WebClientConfig.java
src/main/java/com/realive/controller/chatbot/ChatbotController.java
src/main/java/com/realive/dto/chatbot/ChatApiResponseDTO.java
src/main/java/com/realive/dto/chatbot/ChatRequestDTO.java
src/main/java/com/realive/dto/chatbot/ChatbotRequestDTO.java
src/main/java/com/realive/dto/chatbot/ChatbotResponseDTO.java
src/main/java/com/realive/service/chatbot/ChatbotService.java
src/main/java/com/realive/serviceimpl/chatbot/ChatbotServiceImpl.java

[WIP]AI chatbot 작동만 되게 만듬

---

src/main/java/com/realive/controller/seller/SellerAdminQnaController.java
src/main/java/com/realive/controller/seller/SellerDashboardController.java
src/main/java/com/realive/controller/seller/SellerOrderDeliveryController.java
src/main/java/com/realive/dto/logs/stats/CurrentMonthStatsDTO.java
src/main/java/com/realive/dto/logs/stats/TodayStatsDTO.java
src/main/java/com/realive/dto/order/OrderStatisticsDTO.java
src/main/java/com/realive/dto/sellerqna/SellerQnaStatisticsDTO.java
src/main/java/com/realive/repository/order/OrderRepository.java
src/main/java/com/realive/repository/order/SellerOrderDeliveryRepositoryCustom.java
src/main/java/com/realive/repository/order/SellerOrderDeliveryRepositoryImpl.java
src/main/java/com/realive/repository/seller/SellerQnaRepository.java
src/main/java/com/realive/service/order/SellerOrderService.java
src/main/java/com/realive/service/seller/SellerDashboardService.java
src/main/java/com/realive/service/seller/SellerQnaService.java
src/main/java/com/realive/serviceimpl/order/SellerOrderServiceImpl.java
src/main/java/com/realive/serviceimpl/seller/SellerDashboardServiceImpl.java
src/main/java/com/realive/serviceimpl/seller/SellerQnaServiceImpl.java

[Fix] 판매, 주문, 관리자 QnA 통계 수정

---

build.gradle
src/main/java/com/realive/config/S3Config.java
src/main/java/com/realive/controller/common/FileUploadController.java
src/main/java/com/realive/controller/customer/ReviewController.java
src/main/java/com/realive/controller/customer/ReviewImageController.java
src/main/java/com/realive/dto/review/ReviewCreateRequestDTO.java
src/main/java/com/realive/event/SellerFileUploadHandler.java
src/main/java/com/realive/service/common/FileUploadService.java
src/main/java/com/realive/service/common/S3Uploader.java
src/main/java/com/realive/service/review/crud/ReviewCRUDService.java
src/main/java/com/realive/service/review/crud/ReviewCRUDServiceImpl.java
src/main/java/com/realive/serviceimpl/product/ProductServiceImpl.java
src/main/java/com/realive/serviceimpl/seller/SellerServiceImpl.java

[Feat] 판매자 상품 이미지 AWS S3 업로드 

---

build.gradle
src/main/java/com/realive/controller/customer/ReviewImageController.java
src/main/java/com/realive/controller/seller/SellerPayoutController.java
src/main/java/com/realive/repository/logs/PayoutLogRepository.java
src/main/java/com/realive/service/seller/SellerPayoutService.java
src/main/java/com/realive/serviceimpl/seller/SellerPayoutServiceImpl.java

[Fix] 정산관리 수정

---

src/main/java/com/realive/dto/chatbot/ChatRequestDTO.java

function calling(채팅을 보고 유추해서 관련 메서드 호출)이 제대로 되지 않아 수정중

[WIP] 챗봇 도메인 일탈 제어 및 비로그인 Read Only

---

src/main/java/com/realive/controller/admin/user/AdminQnaController.java
src/main/java/com/realive/dto/seller/SellerQnaResponseDTO.java
src/main/java/com/realive/repository/seller/SellerQnaRepository.java
src/main/java/com/realive/service/admin/user/AdminQnaService.java
src/main/java/com/realive/serviceimpl/admin/user/AdminQnaServiceImpl.java

[Fix]관리자 Q&A 페이지 로직 수정

---

src/main/java/com/realive/controller/admin/AdminSettlementController.java
src/main/java/com/realive/dto/admin/adminsettlement/AdminPayoutDetailResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/AdminPayoutResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/AdminPayoutSearchConditionDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/AdminSettlementPageResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/AdminSettlementStatisticsResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/CommissionDetailResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/DailyPayoutSummaryResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/MonthlyPayoutDetailResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/MonthlyPayoutSummaryResponseDTO.java
src/main/java/com/realive/dto/admin/adminsettlement/SalesDetailResponseDTO.java
src/main/java/com/realive/repository/logs/CommissionLogRepository.java
src/main/java/com/realive/repository/logs/PayoutLogRepository.java
src/main/java/com/realive/repository/logs/SalesLogRepository.java
src/main/java/com/realive/service/admin/AdminSettlementService.java

[Fix] 관리자 정산관리 로직 추가 및 수정

---

src/main/java/com/realive/config/SecurityConfig.java
src/main/java/com/realive/controller/product/ProductController.java
src/main/java/com/realive/dto/product/GenerateProductDescriptionRequestDTO.java
src/main/java/com/realive/dto/product/GenerateProductDescriptionResponseDTO.java
src/main/java/com/realive/repository/product/DeliveryPolicyRepository.java
src/main/java/com/realive/repository/product/ProductRepository.java
src/main/java/com/realive/security/SellerJwtAuthenticationFilter.java
src/main/java/com/realive/service/customer/ProductViewService.java
src/main/java/com/realive/service/customer/ProductViewServiceImpl.java
src/main/java/com/realive/service/product/ProductService.java
src/main/java/com/realive/serviceimpl/chatbot/ChatbotServiceImpl.java
src/main/java/com/realive/serviceimpl/product/ProductServiceImpl.java
src/main/java/com/realive/util/FunctionSchemaFactory.java

아직 불안정한게 물품 추천받을때 카테고리를 정확하게 찾아가지는 못함, 상품 설명 기능은 쓸데없이 길게 설명함

[WIP]챗봇 물품 추천받기, 판매자 물품 설명 생성 기능 구현

---

src/main/java/com/realive/controller/public_api/ProductViewController.java
src/main/java/com/realive/dto/auction/AdminProductDTO.java
src/main/java/com/realive/repository/customer/productview/ProductViewRepository.java
src/main/java/com/realive/service/customer/ProductViewService.java
src/main/java/com/realive/service/customer/ProductViewServiceImpl.java
src/main/java/com/realive/serviceimpl/admin/auction/AuctionServiceImpl.java
src/main/java/com/realive/serviceimpl/admin/product/AdminProductServiceImpl.java
src/main/java/com/realive/serviceimpl/auction/AuctionServiceImpl2.java

[Fix[ 카테고리별 인기상품, 경매 상세 서브 이미지

[Fix] 카테고리별 인기상품, 경매 상세 서브 이미지

---

src/main/java/com/realive/controller/admin/user/AdminQnaController.java
src/main/java/com/realive/dto/sellerqna/SellerQnaResponseDTO.java
src/main/java/com/realive/repository/seller/SellerQnaRepository.java
src/main/java/com/realive/security/customer/JwtTokenProvider.java
src/main/java/com/realive/service/admin/user/AdminQnaService.java
src/main/java/com/realive/serviceimpl/admin/user/AdminQnaServiceImpl.java

[관리자 큐엔에이 검색필터 에러 수정](https://github.com/SSG-Realive/RealBE/commit/40face3d38476a8b7dbc2840766820495bd9d6fa)

[Fix] 관리자 QnA 검색 필터 에러 수정

---

src/main/java/com/realive/controller/chatbot/ChatbotController.java
src/main/java/com/realive/dto/chatbot/ChatRequestDTO.java
src/main/java/com/realive/dto/chatbot/ChatbotRequestDTO.java
src/main/java/com/realive/dto/chatbot/SystemPromptProvider.java
src/main/java/com/realive/service/chatbot/ChatbotService.java
src/main/java/com/realive/serviceimpl/chatbot/ChatbotServiceImpl.java
src/main/java/com/realive/util/FunctionSchemaFactory.java

system prompt 유지보수가 쉽도록 따로 분리, 이전 대화 내용을 대답에 활용 할 수 있도록 수정

[WIP]챗봇 system prompt 따로 분리, session storage 이전 대화 활용
